name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project (with legacy OpenSSL and CI disabled)
        run: CI='' npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "nawabsyscraft@gmail.com"
          git config --global user.name "nawab-syscraft25"
          npm run deploy
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
